### ISSUE TITLE
Misc items

### ISSUE THREAD

**Issue by deitybob12** [Audionut/Upload-Assistant#179]
Thanks for adding the TVMAZE selection via --daily YYYY-MM-DD. It has been working great. However, can you make it ding when that prompt appears? In fact, can you make the tool ding at every prompt (you might want that to be a configurable element in config.py as not everyone wants noise!)

Does or can the tool process AVI files? I've had a few needs for this and Upload_Assistant had errors. I created torrents for those manually. I'm not asking to add this, but is there an existing argument set I should use to get AVI torrents created/uploaded with your tool?

Is there an arg to directly indicate the TVMAZE ID or the TVDB id? I only see args for -tmdb and -imdb but the tool seems to pull/access/use TVMAZE and TVDB while processing. 

Please adjust the -help info if needed. I have noticed that most args only work when they are after the path to the video file, rather than before as the help shows.  If I put some args before the path/file, the error indicates that the argument's value is being perceived as the path/file. 

Thanks again for the awesome tool and your amazing responses to your userbase.

**Comment by Audionut** [comment]
Ding should be easy enough. It's already optioned for existing ding.
```
        # Play the bell sound effect when asking for confirmation
        "sfx_on_prompt": True,
```

AVI is 30+ yrs old and a hacky mess. I understand some sites require AVI for some codecs, but I have no idea why. Seems both arbitrary and unneeded. I have no plans to add support for a limited use case.

tvmaze does not return tmdb, which is a deal breaker. It would need to loop through imdb to then get tmdb. That's not something I feel like exploring, since I tend to create bugs when adding features, and this one smells ripe for quite severe bugs impacting everyone. There is no get_tvdb function at all, relying on the output from other sources.

Frankly, it's boggles my mind that the correct tmdb/imdb/tvdb ID's can link to an "incorrect" tvmaze id.

Actually, whilst typing this out, it occurred to me that I should be able to auto select the searched tvmaze id's if `--tvmaze xxxx`. Let me look into that.

The path before args is a known issue. In my defense, the readme does state `python3 upload.py /downloads/path/to/content --args`.

**Comment by deitybob12** [comment]
Thanks for your consideration. 

I only ask about AVI because I've been working on fulfilling requests, many of which are for shows from 10+ years ago. And the only available files are AVIs. I can get these posted using manual torrent creation, I just wanted to make sure I was not overlooking a setting. 

It's your tool; you decide what it can and will not do. Thanks for letting us use it and consider our suggestions.

**Comment by Audionut** [comment]
I've added tvmaze and tvdb as arguments. Just means that they will use the specified value if given, rather than an auto return from one of the other metadata sources.

If you specify tvmaze, it will chose the searched show that matches.
