### ISSUE TITLE
Uploading HONE releases to ANT - missing Release Group

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#36]
When I upload any WEB-DL with the naming the group HONE releases, ANT never detects the Release Groups and sets it as unknown, hence have to manually edit it after upload!

**Comment by Audionut** [comment]
Look at `wiki.php?action=article&name=api`

ANT pulls the group name from either the filename or the mediainfo, which in either case is not appropriate to modify here. You'll need to complain to them. But I strongly suspect they will not be overly interested in modifying their regex matching because huno has.......strange naming requirements.
